name: 'churn_project'
version: '1.0.0'
config-version: 2

profile: 'churn_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  churn_project:
    staging:
      +materialized: view
      +schema: analytics
    dimensions:
      +materialized: table
      +schema: analytics
    facts:
      +materialized: table
      +schema: analytics
    marts:
      +materialized: table
      +schema: analytics

vars:
  churn_threshold_days: 90
  current_date: '2026-02-10'
